MVC_Commerce/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Commerce.Data.Interfaces;
using MVC_Commerce.Data.Services;
using MVC_Commerce.Models;

namespace MVC_Commerce.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryService _service;
        public CategoryController(ICategoryService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await _service.GetAllAsync();
            return View(categories);
        }

        //GET: Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryName,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(category);
                return RedirectToAction(nameof(Index));
            }
            //ViewData["YazarID"] = new SelectList(_context.Yazarlar, "YazarID", "YazarAd", kitap.YazarID);
            return View(category);
        }

        // GET: Category/Details/1
        public async Task<IActionResult> Details(int id)
        {

            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null)
                return NotFound();


            return View(categoryDetails);
        }

        //GET: Category/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null)
                return NotFound();
            return View(categoryDetails);
        }

        // POST: Category/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CategoryName,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(id, category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        //GET: Category/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null)
                return NotFound();
            return View(categoryDetails);
        }

        // POST: Category/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null) return NotFound();
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MVC_Commerce/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using MVC_Commerce.Data.Cart;
using MVC_Commerce.Data.Interfaces;
using MVC_Commerce.Data.ViewModels;

namespace MVC_Commerce.Controllers
{
    public class OrderController : Controller
    {
        private readonly IProductService _productService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;

        public OrderController(IProductService productService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }
        public async Task<IActionResult> Index()
        {
            string userId = "";

            var orders = await _orderService.GetOrdersByUserIdAsync(userId);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddToShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveFromShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = "";
            string userEmailAdress = "";

            await _orderService.StoreOrderAsync(items, userId, userEmailAdress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

MVC_Commerce/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Commerce.Data.Interfaces;
using MVC_Commerce.Models;
using System.Diagnostics;

namespace MVC_Commerce.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _service;

        public ProductController(IProductService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _service.GetAllAsync(p => p.Category);
            return View(products);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var products = await _service.GetAllAsync(p => p.Category);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult=(from p in products
                                    where p.ProductBrand.ToLower().Contains(searchString.ToLower()) 
                                    || p.ProductName.ToLower().Contains(searchString.ToLower())
                                    || p.ProductDescription.ToLower().Contains(searchString.ToLower())
                                    orderby(p.ProductBrand) descending 
                                    select p).ToList();
                return View("Index",filteredResult);
            }
            return View("Index",products);
        }

        //GET: Product/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var productDetail = await _service.GetProductByIdAsync(id);
            return View(productDetail);
        }

        //GET: Product/Create
        public async Task<IActionResult> Create()
        {
            var productDropdownsData = await _service.GetNewProductDropdownsValues();
            ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "CategoryName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //POST: Product/Create
        public async Task<IActionResult> Create(NewProductVM product)
        {
            if (ModelState.IsValid)
            {
                await _service.AddNewProductAsync(product);
                return RedirectToAction(nameof(Index));

            }
            var productDropdownsData = await _service.GetNewProductDropdownsValues();
            ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "CategoryName");
            return View(product);
        }

        //GET: Product/Edit
        public async Task<IActionResult> Edit(int id)
        {

            var productDetails = await _service.GetProductByIdAsync(id);
            if (productDetails == null)
            {
                return NotFound();
            }

            var response = new NewProductVM()
            {
                Id = productDetails.Id,
                ProductName = productDetails.ProductName,
                ProductDescription = productDetails.ProductDescription,
                ProductPrice = productDetails.ProductPrice,
                ProductBrand = productDetails.ProductBrand,
                CategoryId = productDetails.CategoryId,
                ProductImageURL = productDetails.ProductImageURL,
                ProductQuantity = productDetails.ProductQuantity,
            };
            
            var productDropdownsData = await _service.GetNewProductDropdownsValues();
            ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "CategoryName");
            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //POST: Product/Edit/1
        public async Task<IActionResult> Edit(int id,NewProductVM product)
        {

            if(id!=product.Id) return NotFound();

            if (ModelState.IsValid)
            {
                await _service.UpdateProductAsync(product);
                return RedirectToAction(nameof(Index));

            }
            var productDropdownsData = await _service.GetNewProductDropdownsValues();
            ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "CategoryName");
            return View(product);
        }


    }
}

MVC_Commerce/Views/Shared/_CreateItem.cshtml
@model string;

<div style="position:fixed; right:25px;bottom:75px;">

    <a asp-controller="@Model" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"> Add</i></a>
</div>

MVC_Commerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Amazort</title>
    <link href="https://fonts.googleapis.com/css?family=Bentham|Playfair+Display|Raleway:400,500|Suranna|Trocchi" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/MVC_Commerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand align-content-center" asp-area="" asp-controller="Product" asp-action="Index" style="max-width:10%;"><img src="~/img/amazort-logo.png" width="95%" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav flex-grow-1">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Products</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-gear"></i> Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Category" asp-action="Index">Categories</a>
                                <a class="dropdown-item" asp-controller="User" asp-action="Index">Users</a>
                                <a class="dropdown-item" asp-controller="Comment" asp-action="Index">Comments</a>
                            </div>
                        </li>
                    </ul>
                    <form class="row row-cols-lg-auto g-3 align-items-center" asp-controller="Product" asp-action="Filter">
                        <div class="col-12">
                            <input name="searchString" class="form-control me-2" type="search" placeholder="Search for a product" aria-label="Search">
                        </div>
                        <div class="col-12">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                        </div>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    <a class="btn btn-outline-success my-2 my-sm" asp-controller="Account" asp-action="Login"> <i class="bi bi-box-arrow-in-right"></i>Log in</a>

                    @* User Profile Section*@
                    <div class="dropdown">
                        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-badge"></i> Hello User
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="profile-btn">
                            <li> <a class="dropdown-item" asp-controller="Order" asp-action="Index">
                                    <i class="bi bi-list"></i>Orders
                                </a></li>
                            <li><a class="dropdown-item" >Another action</a></li>
                            <li><a class="dropdown-item">Something else here</a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2022 Copyright:
            <a class="text-reset fw-bold" href="https://www.linkedin.com/in/refikburakakbas/">Refik Burak Akbaş</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>